TestsApp.WEB/Controllers/AdministrationController.cs
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TestsApp.Core;
using TestsApp.WEB.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using TestsApp.Core.Entities;
using TestsApp.Core.Interfaces;
using System;
using System.Security.Claims;

namespace TestsApp.WEB.Controllers
{
    [Authorize(Roles = ApplicationRoles.Administrator)]
    public class AdministrationController : Controller
    {
        #region Constants
        private const string Error = "Error occurred!!!";
        private const string CreatePasswordBody = "Please create password for new user by clicking ";
        private const string CreatePasswordSubject = "Create Password";
        private const string UserExist = "User with such email already exists";
        private const string RolesChanged = "!!! Your permissions are changed by Administrator! You will be logged out!";

        #endregion

        private IUserService UserService;
        private IManagerIdentity ManageService;
        private IEmailService EmailService;
        private ISignalR signalR;
        public AdministrationController(IUserService UserService, IManagerIdentity ManageService, IEmailService EmailService, ISignalR signalR)
        {
            this.UserService = UserService;
            this.ManageService = ManageService;
            this.EmailService = EmailService;
            this.signalR = signalR;
        }

        private IAuthenticationManager authenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        public ActionResult AddUsers()
        {
            AddUserModel model = new AddUserModel();
            model.Roles = new SelectList(ManageService.GetRoles(), "Name", "Name");
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddUsers(AddUserModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await UserService.FindByEmailAsync(model.Email);
                if (user == null)
                {
                    user = new ApplicationUser
                    {
                        Email = model.Email,
                        UserName = model.Name,
                        FullName = model.FullName,
                        EmailConfirmed = true,
                        LockoutEnabled = true,
                        RegistrationDate = DateTime.Now.ToString()
                    };
                    var createUser = await UserService.CreateUser(user);
                    if (createUser.Succeeded)
                    {
                        await UserService.AddToRole(user.Id, ApplicationRoles.RegisteredUser);
                        await UserService.AddToRole(user.Id, model.Role);

                        await EmailService.SendAsync(CreatePasswordMessage(user));
                        return View("SuccessUserAdded");
                    }
                    ModelState.AddModelError(string.Empty, createUser.Errors.FirstOrDefault().ToString());
                    model.Roles = new SelectList(ManageService.GetRoles(), "Name", "Name");
                    return View(model);
                }
                model.Roles = new SelectList(ManageService.GetRoles(), "Name", "Name");
                ModelState.AddModelError(string.Empty, UserExist);
                return View(model);
            }
            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> EditUsersProfile(string Id)
        {
            var user = await UserService.FindByIdAsync(Id);
            var editProfileModel = new EditProfileModel
            {
                Id = Id,
                Email = user.Email,
                Name = user.UserName,
                FullName = user.FullName,
                Roles = await UserService.GetRolesAsync(user.Id)
            };
            return View("UsersProfile", editProfileModel);
        }

        public ActionResult UsersProfile()
        {
            UsersModel users = new UsersModel
            {
                Users = new SelectList(ManageService.GetUsers(), "UserName", "UserName")
            };
            return View(users);
        }

        public ActionResult ManageUsers()
        {
            return View();
        }

        [HttpGet]
        public async Task<ContentResult> GetUserRoles(string Id)
        {
            var user = await UserService.FindByIdAsync(Id);
            var roles = await UserService.GetRolesAsync(user.Id);
            ManageRolesModel manageRoles = new ManageRolesModel
            {
                Roles = GetUsersRolesToList(ManageService.GetRoles(), roles)
            };
            var jsonData = JsonConvert.SerializeObject(manageRoles,
               Formatting.None,
               new JsonSerializerSettings()
               {
                   ReferenceLoopHandling = ReferenceLoopHandling.Ignore
               });
            return Content(jsonData, "application/json");
        }

        [HttpPost]
        public async Task<HttpResponseMessage> ManageUsers(ManageRolesModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await UserService.AddRolesAsync(model.Id, model.SelectedRoles);
                if (result.Succedeed)
                {
                    signalR.NotifyUserAndLogout(model.UserName, string.Concat(model.UserName, RolesChanged));

                    return new HttpResponseMessage(HttpStatusCode.Accepted) ;
                }
            }
            return new HttpResponseMessage(HttpStatusCode.BadGateway);
        }

        public ContentResult GetCurrentUserId()
        {
            string userId = null;
            var claimsIdentity = User.Identity as ClaimsIdentity;
            if (claimsIdentity != null)
            {
                var userIdClaim = claimsIdentity.Claims
                    .FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);

                if (userIdClaim != null)
                {
                    userId = userIdClaim.Value;
                }
            }
            var jsonData = JsonConvert.SerializeObject(userId,
                          Formatting.None,
                          new JsonSerializerSettings()
                          {
                              ReferenceLoopHandling = ReferenceLoopHandling.Ignore
                          });
            return Content(jsonData, "application/json");
        }

        #region Private
        private IList<SelectListItem> GetUsersRolesToList(List<IdentityRole> allRoles, IList<string> userRoles)
        {
            var selectList = new List<SelectListItem>();
            foreach (var element in allRoles)
            {
                if (userRoles.Contains(element.Name))
                {
                    if (element.Name == ApplicationRoles.RegisteredUser)
                    {
                        selectList.Add(new SelectListItem
                        {
                            Value = element.Name,
                            Text = element.Name,
                            Selected = true,
                            Disabled = true
                        });
                    }
                    else
                    {
                        selectList.Add(new SelectListItem
                        {
                            Value = element.Name,
                            Text = element.Name,
                            Selected = true,
                            Disabled = false
                        });
                    }
                }
                else
                {
                    if (element.Name == ApplicationRoles.RegisteredUser)
                    {
                        selectList.Add(new SelectListItem
                        {
                            Value = element.Name,
                            Text = element.Name,
                            Selected = false,
                            Disabled = true
                        });
                    }
                    else
                    {
                        selectList.Add(new SelectListItem
                        {
                            Value = element.Name,
                            Text = element.Name,
                            Selected = false,
                            Disabled = false
                        });
                    }
                }
            }
            return selectList;
        }

        private IdentityMessage CreatePasswordMessage(ApplicationUser user)
        {
            var createPasswordUrl = $@"/Account/CreatePassword?userId={user.Id}";

            IdentityMessage message = new IdentityMessage
            {
                Body = CreatePasswordBody + " <a href=" + CustomConfigurationSection.Settings.BaseUrl + createPasswordUrl + ">here</a>",
                Subject = CreatePasswordSubject,
                Destination = user.Email
            };
            return message;
        }
        #endregion
    }
}

TestsApp.WEB/Views/Administration/AddUsers.cshtml
@model TestsApp.WEB.Models.AddUserModel
@{
    ViewBag.Title = "AddUsers";
}

@using (Html.BeginForm("AddUsers", "Administration", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h2>Create a new user.</h2>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(m => m.FullName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.FullName,  new { @class = "form-control", placeholder = "Enter full name" })
            @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Enter name" })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Enter email" })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Roles, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.Role, Model.Roles,  new { @class = "form-control" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Create User" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestsApp.WEB/Views/Administration/ManageUsers.cshtml
@{
    ViewBag.Title = "ManageUsers";
}

<div id='loading' class="loadAnimation">
    Please wait... <img src="~/Content/ajax-loader.gif" />
</div>
<div class="content">
    <h2>Manage users</h2>
    <hr />
    <div id="boolHelper" hidden></div>
    <p>
        Add new user:
        <a href="/Administration/AddUsers" class="btn btn-success btn-lg">
            <span class="glyphicon glyphicon-user"></span> Add User
        </a>
    </p>
    <div class="form-horizontal">

        <table class='table table-hover'>
            <tbody>
                <tr>
                    <td>
                        <label>User</label>
                    </td>
                    <td class="col-md-4">
                        <select class="form-control" data-bind='options: Users , optionsText: "UserName", value: user , event:{change: GetRoles}, click : FindUser' id="userDropDown"> </select>
                    </td>
                    <td>
                        <div>
                            <input type="checkbox"
                                   name="my-checkbox"
                                   id="toggleBlockUnblock"
                                   data-on="Block"
                                   data-off="Unblock"
                                   checked data-toggle="toggle"
                                   data-width="280"
                                   data-size="large">
                            <br /><br />
                                <label id="result" class="text-danger"></label>
                            </div>
                    </td>
                    <td>
                        <button class="btn btn-primary btn-lg" data-bind='click : goToURL'>
                            <span class="glyphicon glyphicon-edit"></span> Edit User Profile
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
        <div id="allRoles" hidden>
            <table class='table table-hover'>
                <tr>
                    <th>Roles</th>
                    <th>Select role</th>
                </tr>
                <tbody data-bind="foreach: Roles">
                    <tr>
                        <td>
                            <input class="form-control" data-bind='value: Value' disabled />
                        </td>

                        <td>
                            <input type="checkbox" data-bind="checked: Selected, disable : Disabled" />
                        </td>
                    </tr>
                </tbody>
            </table>

            <button class="btn btn-primary" data-bind='click: Save'>
                <span class="glyphicon glyphicon-refresh"></span> Update Roles
            </button>
        </div>
        <div id="rolesForAdmin" hidden>
            <table class='table table-hover'>
                <tr>
                    <th>Roles</th>
                    <th>Select role</th>
                </tr>
                <tbody data-bind="foreach: RolesAdmin">
                    <tr>
                        <td>
                            <input class="form-control" data-bind='value: Value' disabled />
                        </td>

                        <td>
                            <input type="checkbox" data-bind="checked: Selected, disable : Disabled" />
                        </td>
                    </tr>
                </tbody>
            </table>

            <button class="btn btn-primary" data-bind='click: Save'>
                <span class="glyphicon glyphicon-refresh"></span> Update Roles
            </button>
        </div>

    </div>
</div>
<script src="~/Scripts/knockout-3.2.0.js"></script>
<script src="~/Scripts/jquery-1.6.2.min.js"></script>
<script src="~/Scripts/CustomScripts/ManageUsers.js"></script>
<script src="~/Scripts/alertify.js"></script>
<link href="~/Content/alertifyjs/alertify.css" rel="stylesheet" />
<link href="~/Content/alertifyjs/themes/default.css" rel="stylesheet" />

TestsApp.WEB/Views/Administration/SuccessUserAdded.cshtml
@{
    ViewBag.Title = "Add User";
}
<h1>Create user confirmation</h1>

<div class="alert alert-success">
    <strong>User is created successfully!</strong> Email with request to create password is sent to mailbox
</div>

TestsApp.WEB/Views/Administration/UsersProfile.cshtml
@model TestsApp.WEB.Models.EditProfileModel
@{
    ViewBag.Title = "Users Profile";
}

<div>
    <h2>Change users account settings</h2>
    <hr />

    <div class="form-horizontal">
        @Html.AntiForgeryToken()
        <div id="errors" style="color:red;"></div>
        @Html.ValidationSummary("", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.Id, new { id = "UserId" })
        <div class="form-group">
            @Html.LabelFor(m => m.FullName, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.FullName, new { @class = "form-control", id = "FullName" })
                @Html.ValidationMessageFor(model => model.FullName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", id = "User_Name" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @readonly = "true", id = "Email" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">User Roles</label>
            <div class="col-md-10">
                @foreach (var item in Model.Roles)
                {
                    <div class="col-md-10">@item</div><br />
                }
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" id="SaveChanges" class="btn btn-primary">
                    <span class="glyphicon glyphicon-floppy-disk"></span> Save Changes
                </button>

            </div>
        </div>
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/CustomScripts/ChangeUsersProfile.js"></script>
    }
</div>